import type { SettingConfig } from '~~/shared/types/settings'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'ChronoFrame',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'system',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre', 'amap'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'amap.key',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.amap.key.label',
    description: 'settings.map.amap.key.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'amap.securityCode',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.amap.securityCode.label',
    description: 'settings.map.amap.securityCode.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'provider',
    type: 'string',
    defaultValue: '',
    enum: ['mapbox', 'nominatim', 'amap'],
    label: 'settings.location.provider.label',
    description: 'settings.location.provider.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'amap.key',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.amap.key.label',
    description: 'settings.location.amap.key.description',
    isPublic: true,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
  {
    namespace: 'storage',
    key: 'encryption.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.storage.encryption.enabled.label',
    description: 'settings.storage.encryption.enabled.description',
  },
  {
    namespace: 'storage',
    key: 'encryption.key',
    type: 'string',
    defaultValue: '',
    label: 'settings.storage.encryption.key.label',
    description: 'settings.storage.encryption.key.description',
    isSecret: true,
  },
  {
    namespace: 'storage',
    key: 'upload.maxSizeMb',
    type: 'number',
    defaultValue: 512,
    isPublic: true,
    label: 'settings.storage.upload.maxSizeMb.label',
    description: 'settings.storage.upload.maxSizeMb.description',
  },
  // NAMESPACE: oauth
  {
    namespace: 'oauth',
    key: 'github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.oauth.github.enabled.label',
    description: 'settings.oauth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'oauth',
    key: 'github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.oauth.github.clientId.label',
    description: 'settings.oauth.github.clientId.description',
    isSecret: true,
  },
  {
    namespace: 'oauth',
    key: 'github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.oauth.github.clientSecret.label',
    description: 'settings.oauth.github.clientSecret.description',
    isSecret: true,
  },
  // NAMESPACE: analytics
  {
    namespace: 'analytics',
    key: 'gtag.id',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.gtag.id.label',
    description: 'settings.analytics.gtag.id.description',
    isPublic: true,
  },
  {
    namespace: 'analytics',
    key: 'matomo.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.analytics.matomo.enabled.label',
    description: 'settings.analytics.matomo.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'analytics',
    key: 'matomo.url',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.matomo.url.label',
    description: 'settings.analytics.matomo.url.description',
    isPublic: true,
  },
  {
    namespace: 'analytics',
    key: 'matomo.siteId',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.matomo.siteId.label',
    description: 'settings.analytics.matomo.siteId.description',
    isPublic: true,
  },
  // NAMESPACE: upload
  {
    namespace: 'upload',
    key: 'mime.whitelistEnabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.upload.mime.whitelistEnabled.label',
    description: 'settings.upload.mime.whitelistEnabled.description',
  },
  {
    namespace: 'upload',
    key: 'mime.whitelist',
    type: 'string',
    defaultValue: 'image/jpeg,image/png,image/webp,image/gif,image/bmp,image/tiff,image/heic,image/heif,image/vnd.radiance,image/x-exr,video/quicktime,video/mp4',
    label: 'settings.upload.mime.whitelist.label',
    description: 'settings.upload.mime.whitelist.description',
  },
  {
    namespace: 'upload',
    key: 'duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.upload.duplicateCheck.enabled.label',
    description: 'settings.upload.duplicateCheck.enabled.description',
  },
  {
    namespace: 'upload',
    key: 'duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.upload.duplicateCheck.mode.label',
    description: 'settings.upload.duplicateCheck.mode.description',
  },
  // NAMESPACE: security
  {
    namespace: 'security',
    key: 'allowInsecureCookie',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.security.allowInsecureCookie.label',
    description: 'settings.security.allowInsecureCookie.description',
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
